### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by PeterMitrano** [PeterMitrano/my_cookbook#1]
- [ ] iterative search though recepies (narrow down by different qualities)
- [ ] Let users save recipes
- [ ] Query current state 
- [ ] let user add notes to recipes/steps
- [ ] Make more involved tutorial
- [x] Figure out how to host and send audio
- [x] Run, test, and iterate locally- [x] Setup tests
- [x] Make more good tests that actually work
- [ ] still really need moar testz
